apiVersion: v1
kind: Service
metadata:
  name: database-service
  namespace: fincompare
spec:
  selector:
    app: database-service
  ports:
  - port: 8000
    targetPort: 8000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: database-service
  namespace: fincompare
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database-service
  template:
    metadata:
      labels:
        app: database-service
    spec:
      containers:
      - name: database-service
        image: financial-system/database-service:latest
        imagePullPolicy: Never
        env:
        - name: POSTGRES_DB
          value: financial_system
        - name: POSTGRES_USER
          value: system
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: fincompare-secrets
              key: postgres-password
        - name: POSTGRES_HOST
          value: postgres
        - name: POSTGRES_PORT
          value: "5432"
        ports:
        - containerPort: 8000
