apiVersion: v1
kind: Service
metadata:
  name: journey-service
  namespace: fincompare
spec:
  selector:
    app: journey-service
  ports:
  - port: 8004
    targetPort: 8000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: journey-service
  namespace: fincompare
spec:
  replicas: 1
  selector:
    matchLabels:
      app: journey-service
  template:
    metadata:
      labels:
        app: journey-service
    spec:
      containers:
      - name: journey-service
        image: financial-system/journey-service:5.2
        imagePullPolicy: IfNotPresent
        env:
        - name: REDIS_URL
          value: redis://:redis123@redis:6379
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: kafka:9092
        - name: POSTGRES_HOST
          value: postgres
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: fincompare-secrets
              key: postgres-password
        ports:
        - containerPort: 8000
