apiVersion: v1
kind: Service
metadata:
  name: opensearch
  namespace: fincompare
spec:
  selector:
    app: opensearch
  ports:
  - port: 9200
    targetPort: 9200
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: opensearch
  namespace: fincompare
spec:
  serviceName: opensearch
  replicas: 1
  selector:
    matchLabels:
      app: opensearch
  template:
    metadata:
      labels:
        app: opensearch
    spec:
      containers:
      - name: opensearch
        image: opensearchproject/opensearch:2.11.0
        env:
        - name: discovery.type
          value: single-node
        - name: OPENSEARCH_INITIAL_ADMIN_PASSWORD
          value: Admin123!
        - name: plugins.security.disabled
          value: 'true'
        ports:
        - containerPort: 9200
        - containerPort: 9300
