"""Initial safe schema
Revision ID: 6712c0c0675f
Revises: 
Create Date: 2026-07-17 14:07:55.091330
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa

revision: str = '6712c0c0675f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
