"""Add front_products table

Revision ID: 0bf5c1a03945
Revises: 0004
Create Date: 2026-07-14 09:22:46.858410

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0bf5c1a03945'
down_revision = '0004'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('front_products',
    sa.Column('product_id', sa.String(), nullable=False),
    sa.Column('provider_id', sa.String(), nullable=True),
    sa.Column('product_type', sa.String(), nullable=True),
    sa.Column('jurisdiction', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('version', sa.String(), nullable=True),
    sa.Column('last_updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('pricing', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('eligibility_rules', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('features', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('compliance', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('product_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('sector', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('provider', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('product_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('profit_rate', sa.NUMERIC(precision=10, scale=4), autoincrement=False, nullable=True),
    sa.Column('annual_cost', sa.NUMERIC(precision=18, scale=2), autoincrement=False, nullable=True),
    sa.Column('monthly_cost', sa.NUMERIC(precision=18, scale=2), autoincrement=False, nullable=True),
    sa.Column('min_balance', sa.NUMERIC(precision=18, scale=2), autoincrement=False, nullable=True),
    sa.Column('min_age', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('max_age', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('min_income_band', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('key_features', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('jurisdiction', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('source', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('data_freshness', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='products_pkey')
    )
    op.drop_table('front_products')
    # ### end Alembic commands ###
