"""Add missing product columns

Revision ID: 99cde0d7ef2c
Revises: 0bf5c1a03945
Create Date: 2026-07-14 09:38:21.638177

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99cde0d7ef2c'
down_revision = '0bf5c1a03945'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('front_products', sa.Column('schema_hash', sa.String(), nullable=True))
    op.add_column('front_products', sa.Column('effective_date', sa.String(), nullable=True))
    op.add_column('front_products', sa.Column('published_by', sa.String(), nullable=True))
    op.add_column('front_products', sa.Column('approved_by', sa.String(), nullable=True))
    op.add_column('front_products', sa.Column('change_request', sa.String(), nullable=True))
    op.add_column('front_products', sa.Column('previous_version', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('front_products', 'previous_version')
    op.drop_column('front_products', 'change_request')
    op.drop_column('front_products', 'approved_by')
    op.drop_column('front_products', 'published_by')
    op.drop_column('front_products', 'effective_date')
    op.drop_column('front_products', 'schema_hash')
    # ### end Alembic commands ###
