from sqlalchemy.orm import Session
from .models import Appliance, User, UserRole
from .database import SessionLocal, engine, Base
from . import auth

APPLIANCES = [
    # ACs
    {
        "key": "ac_split_1",
        "name": "Split AC 1.5 Ton Inverter",
        "price": "PKR 85,000",
        "brand": "Dawlance",
        "capacity": "1.5 Ton",
        "capacity_num": 1.5,
        "capacity_unit": "Ton",
        "energy": "Inverter",
        "warranty": "2 years",
        "noise": "22 dB",
        "category": "AC",
        "mfg": "ac",
        "origin": "local",
        "variant": "Split",
        "model_year": 2026,
        "is_new": True,
        "source": "Illustrative prototype data",
        "logo": "❄️",
        "annual_energy": 1200,
        "annual_maint": 4000,
        "fuel_type": "electric",
        "gas_cylinders_per_month": 0,
    },
    {
        "key": "ac_window_1",
        "name": "Window AC 2.0 Ton",
        "price": "PKR 65,000",
        "brand": "Gree",
        "capacity": "2.0 Ton",
        "capacity_num": 2.0,
        "capacity_unit": "Ton",
        "energy": "Standard",
        "warranty": "1 year",
        "noise": "28 dB",
        "category": "AC",
        "mfg": "ac",
        "origin": "imported",
        "variant": "Window",
        "model_year": 2025,
        "is_new": False,
        "source": "Illustrative prototype data",
        "logo": "❄️",
        "annual_energy": 1800,
        "annual_maint": 5000,
        "fuel_type": "electric",
        "gas_cylinders_per_month": 0,
    },
    {
        "key": "ac_split_inv",
        "name": "Split AC 1.0 Ton Inverter",
        "price": "PKR 65,000",
        "brand": "LG",
        "capacity": "1.0 Ton",
        "capacity_num": 1.0,
        "capacity_unit": "Ton",
        "energy": "Inverter",
        "warranty": "3 years",
        "noise": "20 dB",
        "category": "AC",
        "mfg": "ac",
        "origin": "imported",
        "variant": "Split",
        "model_year": 2026,
        "is_new": True,
        "source": "Illustrative prototype data",
        "logo": "❄️",
        "annual_energy": 800,
        "annual_maint": 3000,
        "fuel_type": "electric",
        "gas_cylinders_per_month": 0,
    },
    {
        "key": "ac_floor",
        "name": "Floor Standing AC 3 Ton",
        "price": "PKR 120,000",
        "brand": "Daikin",
        "capacity": "3.0 Ton",
        "capacity_num": 3.0,
        "capacity_unit": "Ton",
        "energy": "Inverter",
        "warranty": "3 years",
        "noise": "24 dB",
        "category": "AC",
        "mfg": "ac",
        "origin": "imported",
        "variant": "Floor",
        "model_year": 2026,
        "is_new": True,
        "source": "Illustrative prototype data",
        "logo": "❄️",
        "annual_energy": 2400,
        "annual_maint": 6000,
        "fuel_type": "electric",
        "gas_cylinders_per_month": 0,
    },
    # Coolers
    {
        "key": "cooler_1",
        "name": "Evaporative Cooler 120L",
        "price": "PKR 22,000",
        "brand": "Super Asia",
        "capacity": "120L",
        "capacity_num": 120,
        "capacity_unit": "L",
        "energy": "Standard",
        "warranty": "1 year",
        "noise": "24 dB",
        "category": "Cooler",
        "mfg": "cooler",
        "origin": "local",
        "variant": "Tower",
        "model_year": 2026,
        "is_new": True,
        "source": "Illustrative prototype data",
        "logo": "🌀",
        "annual_energy": 600,
        "annual_maint": 2000,
        "fuel_type": "electric",
        "gas_cylinders_per_month": 0,
    },
    {
        "key": "cooler_80",
        "name": "Evaporative Cooler 80L",
        "price": "PKR 16,000",
        "brand": "National",
        "capacity": "80L",
        "capacity_num": 80,
        "capacity_unit": "L",
        "energy": "Standard",
        "warranty": "1 year",
        "noise": "22 dB",
        "category": "Cooler",
        "mfg": "cooler",
        "origin": "local",
        "variant": "Classic",
        "model_year": 2025,
        "is_new": False,
        "source": "Illustrative prototype data",
        "logo": "🌀",
        "annual_energy": 450,
        "annual_maint": 1500,
        "fuel_type": "electric",
        "gas_cylinders_per_month": 0,
    },
    # Cookers
    {
        "key": "cooker_gas",
        "name": "Gas Cooker 4 Burner",
        "price": "PKR 28,000",
        "brand": "Rinnai",
        "capacity": "4 burners",
        "capacity_num": 4,
        "capacity_unit": "burners",
        "energy": "Gas",
        "warranty": "2 years",
        "noise": "—",
        "category": "Cooker",
        "mfg": "cooker",
        "origin": "local",
        "variant": "Stainless",
        "model_year": 2026,
        "is_new": True,
        "source": "Illustrative prototype data",
        "logo": "🔥",
        "annual_energy": 0,
        "annual_maint": 1500,
        "fuel_type": "gas",
        "gas_cylinders_per_month": 1.5,
    },
    {
        "key": "cooker_electric",
        "name": "Electric Cooker 2 Burner",
        "price": "PKR 15,000",
        "brand": "Panasonic",
        "capacity": "2 burners",
        "capacity_num": 2,
        "capacity_unit": "burners",
        "energy": "Electric",
        "warranty": "1 year",
        "noise": "—",
        "category": "Cooker",
        "mfg": "cooker",
        "origin": "imported",
        "variant": "Induction",
        "model_year": 2026,
        "is_new": True,
        "source": "Illustrative prototype data",
        "logo": "🔥",
        "annual_energy": 400,
        "annual_maint": 1000,
        "fuel_type": "electric",
        "gas_cylinders_per_month": 0,
    },
    {
        "key": "cooker_gas_5",
        "name": "Gas Cooker 5 Burner",
        "price": "PKR 35,000",
        "brand": "Samsung",
        "capacity": "5 burners",
        "capacity_num": 5,
        "capacity_unit": "burners",
        "energy": "Gas",
        "warranty": "2 years",
        "noise": "—",
        "category": "Cooker",
        "mfg": "cooker",
        "origin": "imported",
        "variant": "Premium",
        "model_year": 2025,
        "is_new": False,
        "source": "Illustrative prototype data",
        "logo": "🔥",
        "annual_energy": 0,
        "annual_maint": 1800,
        "fuel_type": "gas",
        "gas_cylinders_per_month": 2,
    },
    {
        "key": "cooker_oven",
        "name": "Cooker with Oven 4+1",
        "price": "PKR 45,000",
        "brand": "Dawlance",
        "capacity": "4 burners + oven",
        "capacity_num": 4,
        "capacity_unit": "burners+oven",
        "energy": "Gas + Electric",
        "warranty": "3 years",
        "noise": "—",
        "category": "Cooker",
        "mfg": "cooker",
        "origin": "local",
        "variant": "Oven combo",
        "model_year": 2026,
        "is_new": True,
        "source": "Illustrative prototype data",
        "logo": "🔥",
        "annual_energy": 300,
        "annual_maint": 2000,
        "fuel_type": "electric+gas",
        "gas_cylinders_per_month": 0.8,
    },
    # Fridges
    {
        "key": "fridge_double",
        "name": "Double Door Fridge 500L",
        "price": "PKR 95,000",
        "brand": "Haier",
        "capacity": "500L",
        "capacity_num": 500,
        "capacity_unit": "L",
        "energy": "Inverter",
        "warranty": "3 years",
        "noise": "18 dB",
        "category": "Fridge",
        "mfg": "fridge",
        "origin": "local",
        "variant": "Double door",
        "model_year": 2026,
        "is_new": True,
        "source": "Illustrative prototype data",
        "logo": "🧊",
        "annual_energy": 650,
        "annual_maint": 3000,
        "fuel_type": "electric",
        "gas_cylinders_per_month": 0,
    },
    {
        "key": "fridge_side",
        "name": "Side by Side Fridge 700L",
        "price": "PKR 145,000",
        "brand": "Samsung",
        "capacity": "700L",
        "capacity_num": 700,
        "capacity_unit": "L",
        "energy": "Inverter",
        "warranty": "3 years",
        "noise": "16 dB",
        "category": "Fridge",
        "mfg": "fridge",
        "origin": "imported",
        "variant": "Side by side",
        "model_year": 2026,
        "is_new": True,
        "source": "Illustrative prototype data",
        "logo": "🧊",
        "annual_energy": 800,
        "annual_maint": 4000,
        "fuel_type": "electric",
        "gas_cylinders_per_month": 0,
    },
    {
        "key": "fridge_french",
        "name": "French Door Fridge 600L",
        "price": "PKR 125,000",
        "brand": "LG",
        "capacity": "600L",
        "capacity_num": 600,
        "capacity_unit": "L",
        "energy": "Inverter",
        "warranty": "3 years",
        "noise": "17 dB",
        "category": "Fridge",
        "mfg": "fridge",
        "origin": "imported",
        "variant": "French door",
        "model_year": 2025,
        "is_new": False,
        "source": "Illustrative prototype data",
        "logo": "🧊",
        "annual_energy": 750,
        "annual_maint": 3500,
        "fuel_type": "electric",
        "gas_cylinders_per_month": 0,
    },
    {
        "key": "fridge_single",
        "name": "Single Door Fridge 300L",
        "price": "PKR 55,000",
        "brand": "Dawlance",
        "capacity": "300L",
        "capacity_num": 300,
        "capacity_unit": "L",
        "energy": "Standard",
        "warranty": "2 years",
        "noise": "20 dB",
        "category": "Fridge",
        "mfg": "fridge",
        "origin": "local",
        "variant": "Single door",
        "model_year": 2025,
        "is_new": False,
        "source": "Illustrative prototype data",
        "logo": "🧊",
        "annual_energy": 450,
        "annual_maint": 2000,
        "fuel_type": "electric",
        "gas_cylinders_per_month": 0,
    },
    # Washers
    {
        "key": "washer_front",
        "name": "Front Load Washer 10kg",
        "price": "PKR 55,000",
        "brand": "LG",
        "capacity": "10kg",
        "capacity_num": 10,
        "capacity_unit": "kg",
        "energy": "Inverter",
        "warranty": "2 years",
        "noise": "22 dB",
        "category": "Washer",
        "mfg": "washer",
        "origin": "imported",
        "variant": "Front load",
        "model_year": 2026,
        "is_new": True,
        "source": "Illustrative prototype data",
        "logo": "🧺",
        "annual_energy": 300,
        "annual_maint": 3000,
        "fuel_type": "electric",
        "gas_cylinders_per_month": 0,
    },
    {
        "key": "washer_top",
        "name": "Top Load Washer 12kg",
        "price": "PKR 40,000",
        "brand": "Dawlance",
        "capacity": "12kg",
        "capacity_num": 12,
        "capacity_unit": "kg",
        "energy": "Standard",
        "warranty": "2 years",
        "noise": "25 dB",
        "category": "Washer",
        "mfg": "washer",
        "origin": "local",
        "variant": "Top load",
        "model_year": 2025,
        "is_new": False,
        "source": "Illustrative prototype data",
        "logo": "🧺",
        "annual_energy": 350,
        "annual_maint": 2500,
        "fuel_type": "electric",
        "gas_cylinders_per_month": 0,
    },
    {
        "key": "washer_front_12",
        "name": "Front Load Washer 12kg",
        "price": "PKR 70,000",
        "brand": "Samsung",
        "capacity": "12kg",
        "capacity_num": 12,
        "capacity_unit": "kg",
        "energy": "Inverter",
        "warranty": "3 years",
        "noise": "20 dB",
        "category": "Washer",
        "mfg": "washer",
        "origin": "imported",
        "variant": "Front load",
        "model_year": 2026,
        "is_new": True,
        "source": "Illustrative prototype data",
        "logo": "🧺",
        "annual_energy": 320,
        "annual_maint": 3500,
        "fuel_type": "electric",
        "gas_cylinders_per_month": 0,
    },
    # TVs
    {
        "key": "tv_4k_55",
        "name": '4K UHD TV 55" Smart',
        "price": "PKR 85,000",
        "brand": "Samsung",
        "capacity": '55"',
        "capacity_num": 55,
        "capacity_unit": '"',
        "energy": "LED",
        "warranty": "2 years",
        "noise": "—",
        "category": "TV",
        "mfg": "tv",
        "origin": "imported",
        "variant": "QLED",
        "model_year": 2026,
        "is_new": True,
        "source": "Illustrative prototype data",
        "logo": "📺",
        "annual_energy": 200,
        "annual_maint": 1000,
        "fuel_type": "electric",
        "gas_cylinders_per_month": 0,
    },
    {
        "key": "tv_4k_65",
        "name": '4K UHD TV 65" Smart',
        "price": "PKR 120,000",
        "brand": "LG",
        "capacity": '65"',
        "capacity_num": 65,
        "capacity_unit": '"',
        "energy": "OLED",
        "warranty": "3 years",
        "noise": "—",
        "category": "TV",
        "mfg": "tv",
        "origin": "imported",
        "variant": "OLED",
        "model_year": 2026,
        "is_new": True,
        "source": "Illustrative prototype data",
        "logo": "📺",
        "annual_energy": 250,
        "annual_maint": 1200,
        "fuel_type": "electric",
        "gas_cylinders_per_month": 0,
    },
    {
        "key": "tv_8k_75",
        "name": '8K QLED TV 75" Smart',
        "price": "PKR 250,000",
        "brand": "Samsung",
        "capacity": '75"',
        "capacity_num": 75,
        "capacity_unit": '"',
        "energy": "QLED",
        "warranty": "3 years",
        "noise": "—",
        "category": "TV",
        "mfg": "tv",
        "origin": "imported",
        "variant": "8K",
        "model_year": 2025,
        "is_new": False,
        "source": "Illustrative prototype data",
        "logo": "📺",
        "annual_energy": 300,
        "annual_maint": 1500,
        "fuel_type": "electric",
        "gas_cylinders_per_month": 0,
    },
    {
        "key": "tv_4k_43",
        "name": '4K UHD TV 43" Smart',
        "price": "PKR 55,000",
        "brand": "TCL",
        "capacity": '43"',
        "capacity_num": 43,
        "capacity_unit": '"',
        "energy": "LED",
        "warranty": "2 years",
        "noise": "—",
        "category": "TV",
        "mfg": "tv",
        "origin": "imported",
        "variant": "4K",
        "model_year": 2026,
        "is_new": True,
        "source": "Illustrative prototype data",
        "logo": "📺",
        "annual_energy": 180,
        "annual_maint": 800,
        "fuel_type": "electric",
        "gas_cylinders_per_month": 0,
    },
    {
        "key": "tv_oled_55",
        "name": 'OLED 55" 4K Smart',
        "price": "PKR 150,000",
        "brand": "Sony",
        "capacity": '55"',
        "capacity_num": 55,
        "capacity_unit": '"',
        "energy": "OLED",
        "warranty": "3 years",
        "noise": "—",
        "category": "TV",
        "mfg": "tv",
        "origin": "imported",
        "variant": "OLED",
        "model_year": 2025,
        "is_new": False,
        "source": "Illustrative prototype data",
        "logo": "📺",
        "annual_energy": 230,
        "annual_maint": 1100,
        "fuel_type": "electric",
        "gas_cylinders_per_month": 0,
    },
]


def ensure_users(db: Session) -> None:
    users = [
        {
            "email": "admin@homecompare.pk",
            "password": "admin123",
            "name": "Admin User",
            "phone": "03001234567",
            "role": UserRole.ADMIN,
        },
        {
            "email": "user@homecompare.pk",
            "password": "user123",
            "name": "Demo User",
            "phone": "03007654321",
            "role": UserRole.USER,
        },
    ]
    for data in users:
        existing = db.query(User).filter(User.email == data["email"]).first()
        if existing:
            continue
        db.add(
            User(
                email=data["email"],
                password_hash=auth.get_password_hash(data["password"]),
                name=data["name"],
                phone=data["phone"],
                role=data["role"],
            )
        )
    db.commit()


def seed_data():
    Base.metadata.create_all(bind=engine)
    db = SessionLocal()
    try:
        ensure_users(db)
        if db.query(Appliance).count() > 0:
            return
        for data in APPLIANCES:
            db.add(Appliance(**data))
        db.commit()
    finally:
        db.close()


if __name__ == "__main__":
    seed_data()
