from __future__ import annotations
import enum
from datetime import datetime
from decimal import Decimal
from sqlalchemy import Boolean, DateTime, Enum, ForeignKey, Index, Integer, JSON, Numeric, String, Text, UniqueConstraint, func
from sqlalchemy.orm import Mapped, mapped_column, relationship
from .database import Base

def EV(e): return Enum(e, values_callable=lambda x:[i.value for i in x])
class UserRole(str,enum.Enum): ADMIN="admin"; APPLICANT="applicant"; SYSTEM="system"
class ProductType(str,enum.Enum):
 CAR_LOAN="car-loan"; PERSONAL_LOAN="personal-loan"; MORTGAGE="mortgage"; HEALTH_INSURANCE="health-insurance"; ACCIDENT_INSURANCE="accident-insurance"; LIFE_INSURANCE="life-insurance"; CREDIT_CARD="credit-card"; BANK_ACCOUNT="bank-account"
class ApplicationStatus(str,enum.Enum):
 DRAFT="draft"; SUBMITTED="submitted"; REVIEW="review"; ELIGIBILITY_CHECK="eligibility-check"; CREDIT_ASSESSMENT="credit-assessment"; OFFER_ISSUED="offer-issued"; ACCEPTED="accepted"; DISBURSED="disbursed"; UNDERWRITING="underwriting"; QUOTED="quoted"; POLICY_ISSUED="policy-issued"; IDENTITY_CHECK="identity-check"; APPROVED="approved"; CARD_ISSUED="card-issued"; KYC_VALIDATION="kyc-validation"; COMPLIANCE_SCREENING="compliance-screening"; ACCOUNT_CREATED="account-created"; ACTIVATED="activated"; ADDITIONAL_INFO="additional-info"; REJECTED="rejected"
class RequestKind(str,enum.Enum): DOCUMENT="document"; TEXT="text"
class RequestStatus(str,enum.Enum): OPEN="open"; SUBMITTED="submitted"; RESOLVED="resolved"; CANCELLED="cancelled"
class DocumentStatus(str,enum.Enum): REQUIRED="required"; UPLOADED="uploaded"; VERIFIED="verified"; REJECTED="rejected"
class User(Base):
 __tablename__='users'; id:Mapped[int]=mapped_column(primary_key=True); public_id:Mapped[str]=mapped_column(String(24),unique=True,index=True); name:Mapped[str]=mapped_column(String(120)); cnic:Mapped[str|None]=mapped_column(String(15),unique=True,nullable=True); username:Mapped[str]=mapped_column(String(80),unique=True,index=True); password_hash:Mapped[str]=mapped_column(String(255)); role:Mapped[UserRole]=mapped_column(EV(UserRole)); is_active:Mapped[bool]=mapped_column(Boolean,default=True); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),server_default=func.now())
class Application(Base):
 __tablename__='applications'; id:Mapped[int]=mapped_column(primary_key=True); application_number:Mapped[str]=mapped_column(String(32),unique=True,index=True); applicant_id:Mapped[int]=mapped_column(ForeignKey('users.id'),index=True); product_type:Mapped[ProductType]=mapped_column(EV(ProductType),index=True); status:Mapped[ApplicationStatus]=mapped_column(EV(ApplicationStatus),index=True,default=ApplicationStatus.DRAFT); amount:Mapped[Decimal|None]=mapped_column(Numeric(18,2),nullable=True); details:Mapped[str|None]=mapped_column(Text,nullable=True); account_data:Mapped[dict|None]=mapped_column(JSON,nullable=True); exception_return_status:Mapped[ApplicationStatus|None]=mapped_column(EV(ApplicationStatus),nullable=True); rejected_from_status:Mapped[ApplicationStatus|None]=mapped_column(EV(ApplicationStatus),nullable=True); status_changed_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),server_default=func.now()); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),server_default=func.now(),index=True); updated_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),server_default=func.now(),onupdate=func.now()); version:Mapped[int]=mapped_column(Integer,default=1,nullable=False); source_system:Mapped[str]=mapped_column(String(50),default='finos'); source_application_id:Mapped[str|None]=mapped_column(String(64),nullable=True); applicant:Mapped[User]=relationship(); status_events:Mapped[list[StatusEvent]]=relationship(back_populates='application',cascade='all, delete-orphan',order_by='StatusEvent.created_at'); documents:Mapped[list[Document]]=relationship(back_populates='application',cascade='all, delete-orphan'); info_requests:Mapped[list[InformationRequest]]=relationship(back_populates='application',cascade='all, delete-orphan'); __mapper_args__={'version_id_col':version}; __table_args__=(Index('ix_app_product_status','product_type','status'), UniqueConstraint('source_system', 'source_application_id', name='uq_source_sys_app_id'))
class StatusEvent(Base):
 __tablename__='status_events'; id:Mapped[int]=mapped_column(primary_key=True); application_id:Mapped[int]=mapped_column(ForeignKey('applications.id',ondelete='CASCADE'),index=True); from_status:Mapped[ApplicationStatus|None]=mapped_column(EV(ApplicationStatus),nullable=True); to_status:Mapped[ApplicationStatus]=mapped_column(EV(ApplicationStatus)); changed_by_id:Mapped[int]=mapped_column(ForeignKey('users.id')); reason:Mapped[str|None]=mapped_column(String(500),nullable=True); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),server_default=func.now()); application:Mapped[Application]=relationship(back_populates='status_events'); changed_by:Mapped[User]=relationship()
class Document(Base):
 __tablename__='documents'; id:Mapped[int]=mapped_column(primary_key=True); application_id:Mapped[int]=mapped_column(ForeignKey('applications.id',ondelete='CASCADE'),index=True); requirement_code:Mapped[str]=mapped_column(String(80)); display_name:Mapped[str]=mapped_column(String(180)); status:Mapped[DocumentStatus]=mapped_column(EV(DocumentStatus),default=DocumentStatus.REQUIRED); original_name:Mapped[str|None]=mapped_column(String(255),nullable=True); stored_name:Mapped[str|None]=mapped_column(String(255),unique=True,nullable=True); mime_type:Mapped[str|None]=mapped_column(String(120),nullable=True); file_size:Mapped[int|None]=mapped_column(Integer,nullable=True); sha256:Mapped[str|None]=mapped_column(String(64),nullable=True); uploaded_by_id:Mapped[int|None]=mapped_column(ForeignKey('users.id'),nullable=True); uploaded_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True),nullable=True); application:Mapped[Application]=relationship(back_populates='documents'); __table_args__=(UniqueConstraint('application_id','requirement_code',name='uq_app_doc_req'),)
class InformationRequest(Base):
 __tablename__='information_requests'; id:Mapped[int]=mapped_column(primary_key=True); public_id:Mapped[str]=mapped_column(String(32),unique=True,index=True); application_id:Mapped[int]=mapped_column(ForeignKey('applications.id',ondelete='CASCADE'),index=True); kind:Mapped[RequestKind]=mapped_column(EV(RequestKind)); label:Mapped[str]=mapped_column(String(255)); document_requirement_code:Mapped[str|None]=mapped_column(String(80),nullable=True); response_text:Mapped[str|None]=mapped_column(Text,nullable=True); status:Mapped[RequestStatus]=mapped_column(EV(RequestStatus),default=RequestStatus.OPEN,index=True); requested_by_id:Mapped[int]=mapped_column(ForeignKey('users.id')); resolved_by_id:Mapped[int|None]=mapped_column(ForeignKey('users.id'),nullable=True); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),server_default=func.now()); submitted_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True),nullable=True); resolved_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True),nullable=True); application:Mapped[Application]=relationship(back_populates='info_requests')
class Communication(Base):
 __tablename__='communications'; id:Mapped[int]=mapped_column(primary_key=True); application_id:Mapped[int]=mapped_column(ForeignKey('applications.id',ondelete='CASCADE'),index=True); sender_id:Mapped[int]=mapped_column(ForeignKey('users.id')); message:Mapped[str]=mapped_column(Text); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),server_default=func.now()); sender:Mapped[User]=relationship(); receipts:Mapped[list[MessageReceipt]]=relationship(back_populates='message',cascade='all, delete-orphan')
class MessageReceipt(Base):
 __tablename__='message_receipts'; id:Mapped[int]=mapped_column(primary_key=True); message_id:Mapped[int]=mapped_column(ForeignKey('communications.id',ondelete='CASCADE'),index=True); user_id:Mapped[int]=mapped_column(ForeignKey('users.id'),index=True); read_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True),nullable=True); message:Mapped[Communication]=relationship(back_populates='receipts'); __table_args__=(UniqueConstraint('message_id','user_id',name='uq_message_user'),)
class AuditLog(Base):
 __tablename__='audit_logs'; id:Mapped[int]=mapped_column(primary_key=True); application_id:Mapped[int|None]=mapped_column(ForeignKey('applications.id',ondelete='SET NULL'),nullable=True,index=True); user_id:Mapped[int]=mapped_column(ForeignKey('users.id')); action:Mapped[str]=mapped_column(String(100)); details:Mapped[dict]=mapped_column(JSON); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),server_default=func.now())
