services:
  backend:
    build: ./backend
    container_name: qwenchat_backend
    ports:
      - "9011:8000"
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - default
      - finos_net
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: qwenchat_frontend
    ports:
      - "9010:80"
    depends_on:
      - backend
    networks:
      - default
    restart: unless-stopped

networks:
  default:
  finos_net:
    external: true
    name: finos_default
