version: "3.8"

services:
  admin-backend:
    build:
      context: ./backend
    container_name: admin-backend
    ports:
      - "9000:8000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always

  admin-frontend:
    build:
      context: ./frontend
    container_name: admin-frontend
    ports:
      - "9001:5174"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - VITE_API_URL=http://localhost:9000
    restart: always
